### PR TITLE
v1.0.0

### PR DESCRIPTION
**Pull request by Gisleburt**
Needs tagging but should be good to go!

Feedback welcome.

### CODE REVIEW

**Comment by antoniocordasco** [comment]
could we get a description of what this PR does please?

**Comment by Gisleburt** [comment]
@antoniocordasco This makes Guzzle an MVP, description of use is in the README.

It shouldn't break BC. Afaik, you don't use it yet but after this you can use it to recursively populate models in the articles api, which should simplify the articles api code significantly.

Example:
1. Query `wp_post` table for basic info -> cursory population of model 
2. Query `wp_postmeta` to get extended info -> run keys and values through guzzle:
    ```rust
    let _leftovers = meta
        .iter()
        .filter_map(|(key, value)| atricle.guzzle((key, value))
        .collect()
    ```

See README for how to annotate models to make it work.

**Comment by Gisleburt** [comment]
Perhaps I should take ownership of the project?

**Comment by JohnField** [comment]
Now merged - sorry for delay!

**Pull request merged**
